module.exports = {
  UserRepository: Symbol.for('UserRepository'),
  UserService: Symbol.for('UserService'),
  AuthorRepository: Symbol.for('AuthorRepository'),
  AuthorService: Symbol.for('AuthorService'),
  CityRepository: Symbol.for('CityRepository'),
  CityService: Symbol.for('CityService'),
  GenreRepository: Symbol.for('GenreRepository'),
  GenreService: Symbol.for('GenreService'),
  MeetingRepository: Symbol.for('MeetingRepository'),
  MeetingService: Symbol.for('MeetingService'),
  PlaylistRepository: Symbol.for('PlaylistRepository'),
  PlaylistService: Symbol.for('PlaylistService'),
  SongRepository: Symbol.for('SongRepository'),
  SongService: Symbol.for('SongService'),
  UserMeetingRepository: Symbol.for('UserMeetingRepository'),
  UserMeetingService: Symbol.for('UserMeetingService'),
  RoleRepository: Symbol.for('RoleRepository'),
  RoleService: Symbol.for('RoleService'),
};
